# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  主题作者: http://arvinxiang.com
  热前端: http://reqianduan.com
  远程.work: http://yuancheng.work

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: reqianduan

# Disqus
# disqus_shortname:

# Baidu share
baidushare: true
