# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  主题作者: http://themes.xiguabaobao.com
  iOS开发博客: http://bawn.github.io/
  tangyumeng's blog: http://tangyumeng.com/
  novsec's blog: http://www.novsec.com/
  小峰网络遨游记: http://xfeng.me/
  沉默紀: http://silenceage.com/

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: 

# Baidu share
baidushare: true